# Generated by Django 2.1.2 on 2018-11-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('critica', models.CharField(max_length=255)),
                ('files', models.CharField(max_length=255)),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
