# Generated by Django 2.1.1 on 2018-09-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Detail',
        ),
        migrations.AddField(
            model_name='player',
            name='Age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='experience',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='heigth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='weigth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
