# Generated by Django 2.1.1 on 2018-09-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenApp', '0002_auto_20180908_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='Detail',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Detalle',
        ),
        migrations.AddField(
            model_name='stadium',
            name='Location',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='opening',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='owner',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='divition',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='foundation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
