# Generated by Django 2.1.3 on 2018-11-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProyecto', models.CharField(max_length=255)),
                ('NombreEmpresa', models.CharField(max_length=255)),
                ('representante', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
                ('inicia', models.DateField()),
                ('finaliza', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('ObjGeneral', models.CharField(max_length=255)),
                ('vision', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('ApellidoMat', models.CharField(max_length=255)),
                ('ApellidoPat', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
