# Generated by Django 2.1.3 on 2018-12-02 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividadName', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Individual', 'Individual'), ('Multiple', 'Multiple')], max_length=255)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignada', 'Asignada'), ('Cancelada', 'Cancelada')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=255)),
                ('antiguedad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProyecto', models.CharField(max_length=255)),
                ('Cliente', models.CharField(max_length=255)),
                ('representante', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('inicia', models.DateField()),
                ('finaliza', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('ObjGeneral', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('userRegistro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.empleados'),
        ),
    ]
