# Generated by Django 2.1.3 on 2018-11-30 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Individual', 'Individual'), ('Multiple', 'Multiple')], max_length=255)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignada', 'Asignada'), ('Cancelada', 'Cancelada')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProyecto', models.CharField(max_length=255)),
                ('representante', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='UsuariosClientes',
        ),
        migrations.AddField(
            model_name='registroproyecto',
            name='proRegistro',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='representante',
            field=models.ManyToManyField(related_name='representant', to='App.Proyecto'),
        ),
    ]
