# Generated by Django 2.1.3 on 2018-12-03 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='finaliza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='inicia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='proyecto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App.RegistroProyecto'),
            preserve_default=False,
        ),
    ]
