# Generated by Django 2.1.3 on 2018-11-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181130_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroproyecto',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
