# Generated by Django 2.1.3 on 2018-11-30 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_registroproyecto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='proRegistro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
