# Generated by Django 2.1.3 on 2018-11-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20181130_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='status',
            field=models.BooleanField(),
        ),
    ]
