# Generated by Django 2.1.3 on 2018-11-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20181130_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='NombreEmpresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='NombreProyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='ObjGeneral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='finaliza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='inicia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='representante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='vision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
