# Generated by Django 2.1.3 on 2018-11-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20181130_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='NombreEmpresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='NombreProyecto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='ObjGeneral',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='departamento',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='finaliza',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='inicia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='representante',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='vision',
            field=models.CharField(max_length=255),
        ),
    ]
