# Generated by Django 2.1.3 on 2018-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20181130_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='representante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
