# Generated by Django 2.1.3 on 2018-11-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20181130_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='finaliza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='inicia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
