# Generated by Django 2.1.3 on 2018-11-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20181130_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroproyecto',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='NombreEmpresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='NombreProyecto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='departamento',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='finaliza',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='inicia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registroproyecto',
            name='representante',
            field=models.CharField(max_length=255),
        ),
    ]
