# Generated by Django 2.1.2 on 2018-10-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fanatics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('adress', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('dateFan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fanatics',
            },
        ),
        migrations.CreateModel(
            name='Palco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=255)),
                ('palcoName', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Palco',
            },
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.AddField(
            model_name='fanatics',
            name='palco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.Palco'),
        ),
        migrations.AddField(
            model_name='fanatics',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.seat'),
        ),
    ]
