# Generated by Django 2.1.2 on 2018-10-07 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanatics',
            name='palco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Examen.Palco'),
        ),
    ]
