# Generated by Django 2.1.2 on 2018-10-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0002_auto_20181007_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanatics',
            name='palco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Examen.Palco'),
        ),
    ]
