# Generated by Django 2.1.3 on 2018-11-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PiezaName', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('typeProduc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Automotriz', 'Automotriz'), ('Micro tecnologia', 'Micro tecnologia')], max_length=255)),
                ('Producto', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('En produccion', 'En produccion'), ('Detenido', 'Detenido')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=255)),
                ('linea', models.CharField(choices=[('Automotriz', 'Automotriz'), ('Micro tecnologia', 'Micro tecnologia')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeProduc', models.CharField(choices=[('Automotriz', 'Automotriz'), ('Micro tecnologia', 'Micro tecnologia')], max_length=255)),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Bloqueado', 'Bloqueado')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='lineaproduccion',
            name='calidad',
            field=models.ManyToManyField(related_name='calidad', to='App.Personal'),
        ),
        migrations.AddField(
            model_name='lineaproduccion',
            name='jefe',
            field=models.ManyToManyField(related_name='jefe', to='App.Personal'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='App.Personal'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='recibe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='App.Personal'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='entregas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Entrega'),
        ),
    ]
