# Generated by Django 2.1.3 on 2018-11-20 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='almacen',
            name='typeProduc',
            field=models.CharField(choices=[('Automotriz', 'Automotriz'), ('Micro tecnologia', 'Micro tecnologia')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estatus',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('No aprobado', 'No aprobado')], max_length=255),
        ),
    ]
