# Generated by Django 2.1.3 on 2018-11-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181120_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Automotriz', 'Automotriz'), ('Micro tecnologia', 'Micro tecnologia')], max_length=255)),
                ('solicito', models.CharField(max_length=255)),
                ('estatus', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerraro', 'Cerraro'), ('Pendiente', 'Pendiente')], max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
