# Generated by Django 2.1.2 on 2018-10-08 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actName', models.CharField(max_length=255)),
                ('lead', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'db_table': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('jobTeam', models.CharField(max_length=255)),
                ('activitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examen.Activities')),
            ],
            options={
                'db_table': 'Personal',
            },
        ),
    ]
